### ISSUE TITLE
I am unable to find fan-control binary after extracting

### ISSUE THREAD

**Issue by eltonajmenezes** [ar51an/raspberrypi-fan-control#2]
Hello

I am unable to find the binary of fan-control after extracting 

This is all that I see
Would appreciate some help
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/66936537/200329749-ea791d9d-6aad-4e6d-a4f5-3973313a6933.png">

**Comment by ar51an** [comment]
Hi,
Latest release of fan-control has the pre-built fan-control binary, compiled with the newest wiringpi c lib ver 2.70. You can download it under the latest release section of this repo:
[https://github.com/ar51an/raspberrypi-fan-control/releases/download/v1.4/raspberrypi-fan-control-release.zip](url)

From your screenshots, you are trying to compile the fan-control code. Error in the shell says it is missing source code. Without source code you cannot compile a binary. Folder/Explorer view screenshot shows there is no fan-control.c. Source code is available under src folder of this repo.

**Comment by eltonajmenezes** [comment]
Thank you for this information.

I have a question regarding the TACHO_PIN since you mentioned that it is disabled in the code.
I would assume that the zip I download from your repo already contains the binary fan-control which is built, correct?
Now if I want the TACHO_PIN to work what do I need to do?
I see there is a file separately on your repo under this location: https://github.com/ar51an/raspberrypi-fan-control/tree/main/src 

I am not sure where it is commented out or what exactly I need to do here.

Also if this is the place for the code and once it is commented out, I would assume I would have to replace the fan-control build in your download but then how do I recompile structure or in what extension do I save it in?

**Comment by eltonajmenezes** [comment]
HI,

So I have a question regarding the values passed through params.conf
I have changed the values for maxtemp
<img width="397" alt="image" src="https://user-images.githubusercontent.com/66936537/200527590-254a429a-e5c4-4ab7-b3ed-5efe62d9246f.png">

But when I check the status via logging I see this
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/66936537/200527736-8ab9d9d4-b62e-404b-a2e8-a877bc2a2e9c.png">


 Over here it shows correctly
 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/66936537/200533817-2c4a5c2d-aa40-4693-b0c2-0eb69e422c2a.png">

So I don't know what I am missing with the log part

I even did a restart manually and of the process but I'm not sure what I'm doing incorrectly


I think it has to do with this part
It will also log when fan is on (at 5 seconds interval) if MaxLevelStore=debug in journald.conf

But where is the location of journald.conf?

**Comment by ar51an** [comment]
> I have changed the values for maxtemp
> But when I check the status via logging I see this

Make sure you changed the values in /opt/gpio/fan/params.conf and save it. Then restart fan-control service. Your screenshot still shows TEMP_MAX=55, which is the default value in params.conf.

> Over here it shows correctly

What is correct here and what is not correct in the previous screenshot? systemctl status by default shows 10 lines. Read systemctl man page.
![image](https://user-images.githubusercontent.com/11185794/200714810-f54fb070-8f57-4e6b-99b5-65367531fd3c.png)


Readme has very clear instructions for every step. Get some familiarity with journal logging. If you do not want fan-control logging to journal at every 5 seconds interval. Edit /etc/systemd/journald.conf and add below line at the very end (default is debug):
`MaxLevelStore=info`

Make sure you know what you are doing, and you really have a _use case_ to enable Tacho. Take a look at the closed issue of this repo.
https://github.com/ar51an/raspberrypi-fan-control/issues/1#issuecomment-1123209972

**Comment by eltonajmenezes** [comment]
Oh My bad; in the part where I said it showed correctly I attached a wrong screenshot
This is it
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/66936537/200722786-0c295919-df0e-41e2-86df-4b7ddec03572.png">

I still don't see a change in the output of the journald.conf unfortunately.

One observation:
The time stamp for the journald.conf shows when I tested without the custom build as you mentioned with the TACHO.
After I rebuilt the script it works but the logging doesn't seem to happen even after a restart of the process or a restart of the system.

My script looks exactly like what you have and have only uncommented the 2 lines for the function calls

**Comment by ar51an** [comment]
Read my previous comment again, if you **DO NOT** want fan-control logging to journal then make that change in journal.conf.

**Comment by eltonajmenezes** [comment]
Gosh, I misinterpreted it. 
But otherwise it is not working as you can see the status of the Fan Speed Control shows the TEMP_MAX=70 whereas the logging does not reflect that despite restarting the process, saving as per what you stated.

Nevertheless I have re-read your statement now: `This program logs to the journal at startup and exit. It will also log when fan is on (at 5 seconds interval) if MaxLevelStore=debug in journald.conf`
**And have enabled this**
MaxLevelStore=debug

The sticking part I guess was the fact that I couldn't locate journald.conf, but now since you clarified that I found it :) 

However even with this there seems to be no output in the log when typing the command. 
sudo journalctl -u fan-control
So something is off.

I redid what I had initially done as well by rebuilding and reinstalling but that log doesn't change at all.

I am wondering if the buffer is full and that's why it is not showing. 🤷🏻‍♂️ Just a guess, I might be wrong


EDIT:

So I realized that it is working

Problem is that old logs are not getting cleared so I keep seeing the old logs
<img width="757" alt="image" src="https://user-images.githubusercontent.com/66936537/200839056-bc4066e6-1396-4153-a800-9ca8ff2397c8.png">


So I figured it out via this site:
https://linuxhandbook.com/clear-systemd-journal-logs/

And now it seems to be working

**Comment by ar51an** [comment]
> **And have enabled this**
> MaxLevelStore=debug

You do not need to do anything in /etc/systemd/journald.conf if you want to see the logging. I mentioned in my earlier comment **_(default is debug)_**

> Problem is that old logs are not getting cleared so I keep seeing the old logs

There was no problem at all. This is how your default journal logging is configured, with persistence. And as I wrote earlier _**Get some familiarity with journal logging.**_

**Comment by eltonajmenezes** [comment]
What I meant to say is that if you use MaxLevelStore=info
Then when you type this command `sudo systemctl status fan-control`
there is no info for TACHO or PWM.

I can understand why here it won't show `sudo journalctl -u fan-control` but it also doesn't for the aforementioned command.

I don't mind the journald not showing anything but when I type this `sudo systemctl status fan-control` I need some output.

Hope this clarified my query
