### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by systmrrr** [ar51an/raspberrypi-fan-control#8]
I'm not good at coding.
How can I fix the error in the screenshot?
I have rpi3modelB.
I followed all instructions.
I managed to run it on rpi3modelB and dietpi operating system in version 3.0. I currently have retropie and I can't run it. please help me.

![2024-03-30_14-44](https://github.com/ar51an/raspberrypi-fan-control/assets/24730797/1f9509f4-ef56-4fc7-8f14-1da3cf0bd577)

**Comment by ar51an** [comment]
Are you getting the error with version 3.0 fan-control in retropie?

If you are using ver 3.0 fan-control. Do you have the pigpio library installed?

Did you compile the fan-control?
(From your screenshot it looks like your system Architecture is 32-bit. The provided releases are for 64-bit)

Paste the output of below cmds:
`cat /etc/systemd/system/fan-control.service`
`ls -l /opt/gpio/fan/`
