### ISSUE TITLE
totally disable fan when under a certain temperature

### ISSUE THREAD

**Issue by ligmaSec** [ar51an/raspberrypi-fan-control#9]
Hi,
First off, thank you for this useful piece of software. This works like a charm. Though, I was wondering if it was possible to have the fan not spin at all when under a certain temperature ?
Something like the gpio-fan dt-overlay (https://github.com/raspberrypi/firmware/blob/c167a3336a2a770ab840e94f2cb1d379d8478c1d/boot/overlays/README#L1446) but with the PWM feature.

Thanks.

**Comment by ar51an** [comment]
> Though, I was wondering if it was possible to have the fan not spin at all when under a certain temperature ?

This is exactly how fan-control works. Fan will not spin below `TEMP_LOW`. You can adjust the `TEMP_LOW` and `TEMP_MAX` according to your desired value in the config file `params.conf`, available in the release.

It is mentioned in the Readme under `Points to Note`.
https://github.com/ar51an/raspberrypi-fan-control?tab=readme-ov-file#points-to-note

**Comment by ligmaSec** [comment]
my fan doesn't stop when the temp is under `TEMP_LOW`, it seems like it just sits at the lowest rpm

**Comment by ar51an** [comment]
What is the TEMP_LOW value you are using? (Try with TEMP_LOW=50 and TEMP_MAX=60)

Which fan-control you are using Wiringpi or Pigpio?

How do you know the fan is not stopping below TEMP_LOW, Did you visually inspect it or checked the logs? (Logs will not print anything when fan is stopped)

I just inspected my fan and it is stopping below TEMP_LOW=40 in my environment. I am using RP4, Noctua fan and Wiringpi fan-control.

**Edit:**
When the fan is spinning it will log after every 5 sec (default delay to adjust fan speed). Take a look at below screenshot of fan-control logs. Logs that are marked in red have difference of more than 5 sec. Whenever the difference is more than 5 secs the fan is not spinning, you can verify this by visually inspecting the fan. It is coded this way to reduce logging when the fan is not spinning.

![fan-logs](https://github.com/ar51an/raspberrypi-fan-control/assets/11185794/a273aca4-e35d-4b56-9d0e-7da92c2e889f)

Please paste the output of your fan-control logs as well.
